services:
  orquestrator:
    build:
      context: orchestrator
      dockerfile: Dockerfile
    container_name: orchestrator
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - equipe-ia
    ports:
      - "3000:3000"


  coder-agent:
    build:
      context: agents/coder
      dockerfile: Dockerfile
    container_name: coder-agent
    restart: unless-stopped
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./data:/app/data
    networks:
      - equipe-ia
    ports:
      - "8001:8000"

  corrector-agent:
    build:
      context: agents/corrector
      dockerfile: Dockerfile
    container_name: corrector-agent
    restart: unless-stopped
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./data:/app/data
    networks:
      - equipe-ia
    ports:
      - "8002:8000"

  reviewer-agent:
    build:
      context: agents/reviewer
      dockerfile: Dockerfile
    container_name: reviewer-agent
    restart: unless-stopped
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./data:/app/data
    networks:
      - equipe-ia
    ports:
      - "8003:8000"

networks:
  equipe-ia:
    driver: bridge