services:
  orquestrator:
    build:
      context: orchestrator
      dockerfile: Dockerfile
    container_name: orchestrator
    restart: "no"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - equipe-ia
    ports:
      - "3000:3000"
    depends_on:
      coder-agent:
        condition: service_healthy
      reviewer-agent:
        condition: service_healthy
      context-agent:
        condition: service_healthy

  coder-agent:
    build:
      context: agents/coder
      dockerfile: Dockerfile
    container_name: coder-agent
    restart: "no"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL_AGENT=${MODEL_AGENT}
    volumes:
      - ./data:/app/data
    networks:
      - equipe-ia
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  reviewer-agent:
    build:
      context: agents/reviewer
      dockerfile: Dockerfile
    container_name: reviewer-agent
    restart: unless-stopped
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL_AGENT=${MODEL_AGENT}
    volumes:
      - ./data:/app/data
    networks:
      - equipe-ia
    ports:
      - "8002:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  context-agent:
    build:
      context: agents/context
      dockerfile: Dockerfile
    container_name: context-agent
    ports:
      - "8003:8000"
    environment:
    - GROQ_API_KEY=${GROQ_API_KEY}
    - MODEL_AGENT=${MODEL_AGENT}
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - equipe-ia


networks:
  equipe-ia:
    driver: bridge